// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnjAcWAej9XI5Dc69QPPacZIjMCOjJ6Zw',
    appId: '1:70889742190:android:ed167e9aa4fb151bd5eb7f',
    messagingSenderId: '70889742190',
    projectId: 'sb-diagnostics-6b790',
    storageBucket: 'sb-diagnostics-6b790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLeZVWaX5btd0ClwXPcUnF9Jbs4UTI3e8',
    appId: '1:70889742190:ios:15a7a1068a9d44f6d5eb7f',
    messagingSenderId: '70889742190',
    projectId: 'sb-diagnostics-6b790',
    storageBucket: 'sb-diagnostics-6b790.appspot.com',
    androidClientId: '70889742190-675cdktphg1u79ijvv8e54cgqs477mf2.apps.googleusercontent.com',
    iosClientId: '70889742190-4ohp7dbgbat4vn3nhii9md6nqqtcqk58.apps.googleusercontent.com',
    iosBundleId: 'com.example.sbDiagnostics',
  );
}
